---
- name: Pull and Run docker image of shubhang123/speminiproject1
  hosts: all
  tasks:
    - name: Pull shubhang123/speminiproject1
      docker_image:
        name: shubhang123/speminiproject1
        source: pull



